version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - dev

sphinx:
  builder: html
  configuration: docs/conf.py

formats:
- htmlzip
- pdf
- epub